### ISSUE TITLE
Array parameter in path

### ISSUE THREAD

**Issue by ViktorPegy** [wI2L/fizz#34]
Prerequisites:
```go
type args struct {
    Id   []int64 `path:"id" validate:"dive,required" explode:"1"`
}

fizz.GET("/:id", []fizz.OperationOption{/*...*//}, tonic.Handler(func(ctx *gin.Context, args *args) error {
  fmt.Println(args)
  return nil
}, 200))
```
Then, when I make a request: `curl "http://localhost:8080/1,2,3"`, I get error: `binding error on field 'Id' of type 'args': strconv.ParseInt: parsing "1,2,3": invalid syntax`.

**Comment by wI2L** [comment]
This is a question related to https://github.com/loopfz/gadgeto

See https://swagger.io/docs/specification/serialization/ **Query parameters** section, and https://github.com/loopfz/gadgeto/blob/66acbcfcb7e86d7d226e759d3609866a3dd11365/tonic/tonic_test.go#L90 for reference.

You are using the `explode` flag the wrong way.
The issue, specifically with your example is that you are trying to explode a value of a path **path** parameter, but this isn't supported, it is only for **query** parameters.
Also, the meaning of `explode:"true"` is to indicate that the query parameters are represented as `?a=1&a=2&a=3`, where `a` is your **query** parameter, and `1,2,3` the values. If explode is `false`, then the query sent should look like this: `?a=1,2,3`.

**Comment by ViktorPegy** [comment]
It also not work with `explode:"false"`. In specification array in path allowed.  
So, I write an issue in https://github.com/loopfz/gadgeto

**Comment by wI2L** [comment]
The issue isn't related to the OpenAPI spec, nor the Fizz generator, but
rather the lack of support for the explode feature of path parameters in
tonic.

**Comment by wI2L** [comment]
For reference, the path parameters extraction function can be found [here](https://github.com/loopfz/gadgeto/blob/66ad4638c25c77275b47b89dd23d013c36aaae48/tonic/tonic.go#L301).
It doesn't support the `ExplodeTag` tag, as the `extractQuery` [function](https://github.com/loopfz/gadgeto/blob/66ad4638c25c77275b47b89dd23d013c36aaae48/tonic/tonic.go#L259) does.

**Comment by wI2L** [comment]
@ViktorPegy see https://github.com/loopfz/gadgeto/pull/63, a PR has started to address what we talked about.
