### ISSUE TITLE
Endpoints with colon(:)

### ISSUE THREAD

**Issue by hmajid2301** [wI2L/fizz#41]
Hi, is it possible to use endpoints that have a `:` in the path? 

Such as: 

- `/game/{name}:enable`

If I try:

```go
grp.PUT("/:name:enabled", []fizz.OperationOption{
....
}, tonic.Handler(controllers.DisableGameType, http.StatusOK))
```

I get the following error

```
panic: error while generating OpenAPI spec on operation PUT /:name:disable: semantic error for path /game/{name:disable}: declared path parameter name:disable needs to be defined at operation level
```

Thanks

**Comment by wI2L** [comment]
This is a gin limitation. See this issue:
https://github.com/gin-gonic/gin/issues/1432

Le mar. 13 oct. 2020 à 18:58, Haseeb Majid <notifications@github.com> a
écrit :

**Comment by hmajid2301** [comment]
Yeh I thought I remember reading the colon approach was preferred for actions in some rest guide. But you are correct `/enable` hardly makes a difference thanks
