### ISSUE TITLE
'Any' type with interface{}

### ISSUE THREAD

**Issue by rw-access** [wI2L/fizz#51]
I have an API that has one field that can return an arbitrary data type. Normally, I would avoid that scenario as much as possible, but in my case it does make sense to have this behavior.

On my output struct, I have a field `result interface{}`, but when generating the OpenAPI 3.0 schema, it's completely dropped. I think ideally, this would generate a jsonschema of `"type":["number","string","boolean","object","array", "null"]`

Is there to express this? If not, do you mind if I make a PR to add this behavior?

**Comment by rw-access** [comment]
FWIW I can make `"type": "any"` work but that's not valid JSON schema.
```golang
var ifaceptr *interface{}
fizz.Generator().OverrideTypeName(reflect.TypeOf(ifaceptr).Elem(), "any")
```

```json
"result": {
    "type": "any",
    "description": "The result object which can be any valid JSON type",
    "format": "any"
},
```

**Comment by wI2L** [comment]
@rw-access 

Yes, as you can see [here](https://github.com/wI2L/fizz/blob/7bb66a13f190625938c8f323ce2efc619e4a1f83/openapi/generator.go#L863), when a data type is not supported, it is skipped add an error is added to the generator's internal list. You should see a `TypeError` if you print the content of [`fizz.Errors`](https://pkg.go.dev/github.com/wI2L/fizz#Fizz.Errors).

That's clearly a limitation that could be lifted. The [`DataTypeFromType`](https://github.com/wI2L/fizz/blob/master/openapi/types.go#L160) function could return a `TypeAny` value to represent the `interface{}` Go type, which could then generate an OpenAPI Schema that represents all JSON values.

However, your mention of the jsonschema `"type":["number","string","boolean","object","array", "null"]` is invalid according to the OpenAPI scpec. See https://swagger.io/specification/#openapi-object, it specifies:
> type - Value MUST be a string. Multiple types via an array are not supported. 

I'm thinking that producing a schema that contains a `oneOf` property validating one of `number`, `string`, `boolean`, `object` or `array` type could do the trick.

**Comment by rw-access** [comment]
Ah good catch with `oneOf`, that makes more sense. I was looking at the generator code and it looks like it shouldn't be _too_ bad to add. Mind if I give it a shot?

**Comment by wI2L** [comment]
Just found that there already is a support for "any types" in the OpenAPI spec: https://swagger.io/docs/specification/data-models/data-types/.

So the above would stand, but instad of messing with `oneOf`, we could just create a constant schema value like so:
```
anySchema = &Schema{
  Nullable: true,
  Description: "Can be any value, including null",
}
```
