### ISSUE TITLE
No scopes unavailable in OAuth2 flow

### ISSUE THREAD

**Issue by jpedrofontes** [wI2L/fizz#86]
Hello, If an application does not use the scopes property in an oauth2 security flow, the property should be present in the output openapi.yaml to not cause a parsing error in Swagger. 

![image](https://user-images.githubusercontent.com/11562899/183448554-9bdfaabb-2077-4008-8c62-a4c480d54592.png)

It should be represented as an empty object:

`scopes: {}`

**Comment by wI2L** [comment]
https://github.com/wI2L/fizz/pull/87 should fix the problem.
